### ISSUE TITLE
Course Assignments

### ISSUE THREAD

**Issue by chrismeier30** [UmarUFLIP/JavaScriptCourseJS#2]
### Assignments

**Section 1: Welcome, Welcome, Welcome!**
- [x] Watch Lectures 1 thru 5

**Section 2: JavaScript Fundamentals - Part 1**
- [x] Watch Lectures 6 thru 10
- [x] Section 2 Lesson 10 Values and Variables
- [x] Watch Lectures 11 thru 12
- [x] Section 2 Lesson 12 Data Types
- [x] Watch Lecture 13 let, const and var
- [x] Section 2 Lesson 13 let, const and var
- [x] Watch Lectures 14 Basic Operators
- [x] Section 2 Lesson 14 Basic Operators
- [x] Watch Lectures 15 Operator Precedence
- [x] Coding Exercise 1: Section 2 Coding Challenge 1
- [x] Watch Lecture 16: Strings and Template Literals
- [x] Section 2 Lesson 16: Strings and Template Literals
- [x] Watch Lectures 17: Taking Decisions: if/else Statements
- [x] Section 2 Lesson 17: Taking Decisions: if / else Statements
- [x] Coding Exercise 2: Section 2 Coding Challenge 2
- [x] Watch Lectures 18: Type Conversion and Coercionz
- [x] Section 2 Lesson 18: Type Conversion and Coercion
- [x] Watch Lectures 19: Truthy and Falsy Values
- [x] Watch Lectures 20: Equality Operators: == vs. ===
- [x] Section 2 Lesson 20 Equality Operators: == vs. ===
- [x] Watch Lectures 21: Boolean Logic
- [x] Watch Lectures 22: Logical Operators
- [x] Section 2 Lesson 22: Logical Operators
- [x] Coding Exercise 3: Section 2 Coding Challenge 3
- [x] Watch Lectures 23: The switch Statement
- [x] Section 2 Lesson 23 The switch Statement
- [x] Watch Lectures 24: Statements and Expressions
- [x] Watch Lectures 25: The Conditional (Ternary) Operator
- [x] Section 2 Lesson 25: The Conditional (Ternary) Operator
- [x] Coding Exercise 4: Section 2 Coding Challenge 4
- [x] Watch Lecture 26: JavaScript Releases: ES5, ES6+, and ESNext

**Section 3: JavaScript Fundamentals - Part 2**
- [x] Watch Lecture 27: Section Intro
- [x] Watch Lecture 28: Activating Strict Mode
- [x] Watch Lecture 29: Functions
- [x] Section 3 Lesson 29: Functions
- [x] Watch Lectures 30: Function Declarations vs. Expressions
- [x] Section 3 Lesson 30 Function Declarations vs. Expressions
- [x] Watch Lecture 31: Arrow Functions
- [x] Section 3 Lesson 31: Arrow Functions
- [x] Watch Lectures 32: Functions Calling Other Functions
- [x] Section 3 Lesson 32: Functions Calling Other Functions
- [x] Watch Lectures 33: Reviewing Functions
- [x] Coding Exercise 5: Section 3 Coding Challenge 1
- [x] Watch Lecture 34: Introduction to Arrays
- [x] Section 3 Lesson 34 Introduction to Arrays
- [x] Watch Lecture 35: Basic Array Operations (Methods)
- [x] Section 3 Lesson 35 Basic Array Operations (Methods)
- [x] Coding Exercise 6:  Section 3 Coding Challenge 2
- [x] Watch Lecture 36: Introduction to Objects
- [x] Section 3 Lesson 36 Introduction to Objects
- [x] Watch Lectures: 37 Dot vs. Bracket Notation
- [x] Section 3 Lesson 37 Dot vs. Bracket Notation
- [x] Watch Lecture 38: Object Methods
- [x] Section 3 Lesson 38 Object Methods
- [x] Coding Exercise 7: Section 3 Coding Challenge 3
- [x] Watch Lecture 39: Iteration: The for Loop
- [x] Section 3 Lesson 39 Iteration: The for Loop
- [x] Watch Lecture 40: Looping Arrays, Breaking and Continuing
- [x] Section 3 Lesson 40 Looping Arrays, Breaking and Continuing
- [x] Watch Lecture 41: Looping Backwards and Loops in Loops
- [x] Section 3 Lesson 41Looping Backwards and Loops in Loops
- [x] Watch Lecture 42: The while Loop
- [x] Section 3 Lesson 42 The while Loop
- [x] Coding Exercise 8: Section 3 Coding Challenge 4

**Section 4: How to Navigate This Couse**
Skip Section

**Section 5: Developer Skills & Editor Setup**
- [x] Download Starter code from 03-Developer-Skills [https://github.com/jonasschmedtmann/complete-javascript-course]
- [x] Watch Lecture 47 Setting up Prettier and VS Code
- [x] Watch Lecture 48: Install Node.js and Setting Up a Dev Environment
- [x] Install Live Server thru VS code,
- [x] Install Node.js
- [x] Install Live Server NPM 
- [x] Watch Lecture 49 Learning How to Code
- [x] Sign up on codewars.com. Join clan UFLIP. 
- [x] Section 5 Lesson 49 codewars.com Kata Challenge.
- [x] Watch Lecture 50: How to Think Like a Developer: Become a Problem Solver!
- [x] Watch Lecture 51 Using Google, StackOverflow and MDN
- [x] Section 5 Lesson 51 codewars.com Kata Challenge. Use and show the 4 steps to solve any problem
- [x] Watch Lecture 52: Debugging (Fixing Errors)
- [x] Watch Lecture 53: Debugging with the console and Breakpoints
- [x] Section 5 Lecture 54 Debug code for issue ticket #13
- [x] Coding Exercise 9: Section 5 Coding Challenge 1

**Section 6: HTML & CSS Crash Course**
- [x] Watch Lecture 55 (Install VS Code Extensions Auto Close Tag and Auto Rename Tag)
- [x] Section 6 Lecture 55 Build Simple HTML Page #3
- [x] Watch Lecture 56: Basic HTML Structure and Elements
- [x] Section 6 Lecture 56 Create an HTML page with a Simple Form #4
- [x] Watch Lecture 57 Attributes, Classes and IDs
- [x] Section 6 Lecture 57 Add Styling to the Idea From #5
- [x] Watch Lecture 58: Basic Styling with CSS
- [x] Section 6 Lecture 58: Add Additional Style to the Idea Form #6
- [x] Watch Lecture 59: Introduction to the CSS Box Model

**Section 7: JavaScript in the Browser: DOM and Events Fundamentals**
### Project 1 Guess My Number
- [x] Section 7 Project 1 - Build a Guess My Number App
    - [x] Create a new github branch Section 7 Project 1
    - [x] In the Readme explain what the Applicaiton is and what it does 
    - [x] Add four files to this branch (.prettierrc, index.html, script.js, style.css). 
    - [x] Go to the course starter code for this project.  https://github.com/jonasschmedtmann/complete-javascript-course/tree/master/05-Guess-My-Number/starter
    - [x] Open each file on github. Copy the code from github and paste the code into the corresponding filename in your github branch
    - [x] Following along with lectures 62 thru 70 to complete the project
- [x] Watch Lecture 62: PROJECT 1: Guess My Number!
- [x] Watch Lecture 63: What's the DOM and DOM Manipulation
- [x] Watch Lecture 64: Selecting and Manipulating Elements
- [x] Watch Lecture 65: Handling Click Events
- [x] Watch Lecture 66: Implementing the Game Logic
- [x] Watch Lecture 67: Manipulating CSS Styles
- [x] Coding Exercise 10: Section 7 Coding Challenge 1 (A new branch is not needed. Complete the coding challenge in the branch created for the project). Add the coding challenge to the readme doc in your branch.

🛑Do not continue until Section 7 Coding Challenge 1 has been reviewed and marked completed

- [x] Watch Lecture 69 Implementing Highscores
- [x] Watch Lecture 70: Refactoring Our Code:  The DRY Principle

🛑Do not continue until your finished code has been reviewed and marked completed. Create an issue ticket for Project 1 Guess My Number. In the issue ticket describe the project and explain all the functionality that is contained within your application. Include screenshots of the finish web application in the issue ticket. Also use markdown to format the text in the issue ticket (https://www.markdownguide.org/basic-syntax/).  Assign the ticket to yourself, label the issue as Assignment.  Add a comment mentioning @chrismeier30 that the project has been completed when you are ready for it be reviewed. To help create your first ticket, you can reference this example ticket (#9 Issue Ticket Example)

### Project 2 Modal Window
- [x] Section 7 Project 2 - Modal Window
    - [x] Create a new github branch Section 7 Project 2 Lecture
    - [x] In the Readme explain what the Applicaiton is and what it does 
    - [x] Add four files to this branch (.prettierrc, index.html, script.js, style.css). 
    - [x] Go to the course starter code for this project.  https://github.com/jonasschmedtmann/complete-javascript-course/tree/master/06-Modal/starter
    - [x] Open each file on github. Copy the code from github and paste the code into the corresponding filename in your github branch
    - [x] Following along with lectures 71 thru 73 to complete the lecture project
- [x] Watch Lecture 71: PROJECT 2 Modal Window
- [x] Watch Lecture 72: Working With Classes
- [x] Watch Lecture 73: Handling and "Esc" Keypress Event
- [x] Push the completed code for the Section 7 Project 2 Lecture
- [x] Section 7 Project 2 #7

🛑Do not continue until Section 7 Project 2 #7 has been reviewed and marked completed

### Project 3 Pig Game
- [x] Section 7 Project 3 - Pig Game
    - [x] Create a new github branch Section 7 Project 3 Lecture
    - [x] In the Readme explain what the Applicaiton is and what it does 
    - [x] Add four files to this branch (.prettierrc, index.html, script.js, style.css). 
    - [x] Go to the course starter code for this project.  https://github.com/jonasschmedtmann/complete-javascript-course/tree/master/07-Pig-Game/starter
    - [x] Open each file on github. Copy the code from github and paste the code into the corresponding filename in your github branch
    - [x] Following along with lectures 74 thru 78 to complete the lecture project
- [x] Watch Lecture 74: PROJECT 3 Pig Game
- [x] Watch Lecture 75: Rolling the Dice
- [x] Watch Lecture 76: Switching the Active Player
- [x] Watch Lecture 77: Holding Current Score
- [x] Watch Lecture 78: Resetting the Game
- [x] Push the completed code for the Section 7 Project 3 Lecture
- [x] Section 7 Project 3 #8

🛑Do not continue until Section 7 Project 3 #10 has been reviewed and marked completed

**Section 8: How JavaScript Works Behind the Scenes**
- [x] Watch Lecture 81: An High-Level Overview of Javascript
- [x] Watch Lecture 82: The JavaScript Engine and Runtime
- [x] Watch Lecture 83: Executing Contexts and The Call Stack
- [x] Watch Lecture 84: Scope and the Scope Chain
- [x] Watch Lecture 85: Scoping in Practice
- [x] Watch Lecture 86: Variable Environment: Hoisting and The TDZ
- [x] Watch Lecture 87: Hoisting and TDZ in Practice
- [x] Section 8 Lesson 87 #10
- [x] Watch Lecture 88: The this Keyword
- [x] Watch Lecture 89: The this Keyword in Practice
- [x] Watch Lecture 90: Regular Functions vs Arrow Functions
- [x] Section 8 Lesson 90 #11
- [x] Watch Lecture 91: Primitives vs. Objects (Primitive vs Reference Types)
- [x] Watch Lecture 92: Primitives vs. Objects in Practice

**Section 9: Data Structures, Modern Operators and Strings**
- [x] Watch Lecture 95: Destructuring Arrays
- [x] Watch Lecture 96: Destructuring Objects
- [x] Watch Lecture 97: The Spread Operator (...)
- [x] Watch Lecture 98: Rest Pattern and Parameters
- [x] Watch Lecture 99: Short Circuiting (&& and II)
- [x] Watch Lecture 100: The Nullish Coalescing Operator (??)
- [x] Watch Lecture 101: Logical Assignment Operators
- [x] Section 9 Coding Challenge 1

🛑Do not continue until Section 9 Coding Challenge 1 has been completed

- [x] Watch Lecture 102: Coding Challenge 1 
- [x] Watch Lecture 103: Looping Arrays: The for-of Loop
- [x] Watch Lecture 104: Enhanced Object Literals
- [x] Watch Lecture 105: Optional Chaining (?.)
- [x] Watch Lecture 106: Looping Objects: Object Keys, Values and Entries
- [x] Section 9 Coding Challenge 2

🛑Do not continue until Section 9 Coding Challenge 2 has been completed

- [x] Watch Lecture 107: Coding Challenge 2
- [x] Watch Lecture 108: Sets
- [x] Watch Lecture 109: Maps: Fundamentals
- [x] Watch Lecture 110: Maps: Iteration
- [x] Watch Lecture 111: Summary: Which Data Structure to Use?
- [x] Section 9 Coding Challenge 3

🛑Do not continue until Section 9 Coding Challenge 3 has been completed

- [x] Watch Lecture 112: Coding Challenge 3
- [x] Watch Lecture 113: Working With Strings - Part 1
- [x] Watch Lecture 114: Working With Strings - Part 2
- [x] Watch Lecture 115: Working With Strings - Part 3
- [x] Section 9 Coding Challenge 4

🛑Do not continue until Section 9 Coding Challenge 4 has been completed

- [x] Watch Lecture 116: Coding Challenge 4
- [x] Watch Lecture 117: String Methods Practice

**Section 10: A closer Look at Functions**
- [x] Watch Lecture 120: Default Parameters
- [x] Watch Lecture 121: How Passing Arguments Works: Value vs. Reference
- [x] Watch Lecture 122: First-Class and Higher-Order Functions 
- [x] Watch Lecture 123: Functions Accepting Callback Functions
- [x] Watch Lecture 124: Functions Returning Functions
- [x] Watch Lecture 125: The call and apply Methods
- [x] Watch Lecture 126: The bind Method
- [x] Section 10 Coding Challenge 1

🛑Do not continue until Section 10 Coding Challenge 1 has been completed

- [x] Watch Lecture 127: Coding Challenge 1
- [x] Watch Lecture 128: Immediately Invoked Function Expressions (IIFE)
- [x] Watch Lecture 129: Closures
- [x] Watch Lecture 130: More Closure Examples
- [x] Section 10 Coding Challenge 2

🛑Do not continue until Section 10 Coding Challenge 2 has been completed

- [x] Watch Lecture 131: Coding Challenge 2

**Section 11: Working with Arrays**

- [x] Watch Lecture 134: Simple Array Methods
- [x] Watch Lecture 135: The new at Method
- [x] Watch Lecture 136: Looping Arrays: forEach
- [x] Watch Lecture 137: forEach With Maps and Sets
- [x] [Download Starter files](https://github.com/jonasschmedtmann/complete-javascript-course/tree/master/11-Arrays-Bankist/starter) for Bankist App. Follow along with lectures (146 thru 164) 
- [x] Watch Lecture 138: PROJECT: "Bankist" App
- [x] Watch Lecture 139: Creating DOM Elements
- [x] Section 11 Coding Challenge 1

🛑Do not continue until Section 11 Coding Challenge 1 has been completed

- [x] Watch Lecture 140: Coding Challenge 1
- [x] Watch Lecture 141: Data Transformations: map, filter, reduce
- [x] Watch Lecture 142: The map Method
- [x] Watch Lecture 143: Computing Usernames
- [x] Watch Lecture 144: The Filter Method
- [x] Watch Lecture 145: The Reduce Method
- [x] Section 11 Coding Challenge 2

🛑Do not continue until Section 11 Coding Challenge 2 has been completed

- [x] Watch Lecture 146: Coding Challenge 2
- [x] Watch Lecture 147: The Magic of Chaining Methods'
- [x] Section 11 Coding Challenge 3

🛑Do not continue until Section 11 Coding Challenge 3 has been completed

- [x] Watch Lecture 148: Coding Challenge 3
- [x] Watch Lecture 149: The find Method
- [x] Watch Lecture 150: Implementing Login
- [x] Watch Lecture 151: Implementing Transfers
- [x] Watch Lecture 152: The findIndexMethod
- [x] Watch Lecture 153: some and every (also include)
- [x] Watch Lecture 154: flat and flatMap
- [x] Watch Lecture 155: Sorting Arrays
- [x] Watch Lecture 156: More Ways of Creating and Filling Arrays
- [x] Section 11 Project: Create a new branch for the "Bankist" App project and push the finished code. In the readme file describe the project and include a screenshot of the UI.
- [x] Watch Lecture 157: Summary: Which Array Method to Use?
- [x] Watch Lecture 158: Array Methods Practice
- [x] Section 11 Coding Challenge 4

🛑Do not continue until Section 11 Coding Challenge 4 has been completed

- [x] Watch Lecture 159: Coding Challenge 4

**Section 12: Numbers, Dates, Intl and Timers**

- [x] Create a new branch for the Bankist App created in **Section 11**. Follow along with lectures (170 thru 181) 
- [x] Watch Lecture 162: Converting and Checking Numbers
    - [x] Update the starter data in your Bankist App to match the new data provided by Jonas
- [x] Watch Lecture 163: Math and Rounding
- [x] Watch Lecture 164: The Remainder Operator
- [x] Watch Lecture 165: Numeric Separators
- [x] Watch Lecture 166: Working with BigInt
- [x] Watch Lecture 167: Creating Dates
- [x] Watch Lecture 168: Adding Dates to "Bankist" App
- [x] Watch Lecture 169: Operations With Dates
- [x] Watch Lecture 170: Internationalizing Dates (Intl)
- [x] Watch Lecture 171: Internationalizing Numbers (Intl)
- [x] Watch Lecture 172: Timers: setTimeout and setInterval
- [x] Watch Lecture 173: Implementing a Countdown Timer
- [x] Section 12 Project: Push the updated code for the Bankist App to your new branch, Section12Project

**Section 13: Advanced DOM and Events**

- [x] [Download Starter files](https://github.com/jonasschmedtmann/complete-javascript-course/tree/master/13-Advanced-DOM-Bankist/starter) for "Bankist" Website. Follow along with lectures (184 thru 203) 
- [x] Watch Lecture 176: PROJECT: "Bankist" Website
- [x] Watch Lecture 177: How the DOM Really Works
- [x] Watch Lecture 178: Selecting, Creating, and Deleting Elements
- [x] Watch Lecture 179: Styles, Attributes and Classes
- [x] Watch Lecture 180: Implementing smooth Scrolling
- [x] Watch Lecture 181: Types of Events and Event Handlers
- [x] Watch Lecture 182: Event Propagation: Bubbling and Capturing
- [x] Watch Lecture 183: Event Propagation in Practice
- [x] Watch Lecture 184: Event Delegation: Implementing Page Navigation
- [x] Watch Lecture 185: DOM Traversing
- [x] Watch Lecture 186: Building a Tabbed Component
- [x] Watch Lecture 187: Passing Arguments to Event Handlers
- [x] Watch Lecture 188: Implementing a Sticky Navigation: The Scroll Event
- [x] Watch Lecture 189: A Better Way: The Intersection Observer API
- [x] Watch Lecture 190: Revealing Elements on Scroll
- [x] Watch Lecture 191: Lazy Loading Images 
- [x] Watch Lecture 192: Build a Slider Component: Part 1
- [x] Watch Lecture 193: Build a Slider Component: Part 2
- [x] Watch Lecture 194: Lifecycle DOM Events
- [x] Watch Lecture 195: Efficient Script Loading: defer and async
- [x] Section 13 Project: Push the updated code for the "Bankist" Website to your new branch, Section13Project

**Section 14: Object-Oriented Programming (OOP) With JavaScript**

- [x] Watch Lecture 198: What is Object-Oriented Programming
- [x] Watch Lecture 199: OOP in JavaScript
- [x] Watch Lecture 200: Constructor Functions and the new Operator
- [x] Watch Lecture 201: Prototypes
- [x] Watch Lecture 202: Prototypal Inheritance and the Prototype Chain
- [x] Watch Lecture 203: Prototypal Inheritance on Built-In Objects
- [x] Section 14 Coding Challenge 1

🛑Do not continue until Section 14 Coding Challenge 1 has been completed

- [x] Watch Lecture 204: Coding Challenge 1
- [x] Watch Lecture 205: ES6 Classes
- [x] Watch Lecture 206: Setters and Getters
- [x] Watch Lecture 207: Static Methods
- [x] Watch Lecture 208: Object.create
- [x] Section 14 Coding Challenge 2

🛑Do not continue until Section 14 Coding Challenge 2 has been completed

- [x] Watch Lecture 209: Coding Challenge 2
- [x] Watch Lecture 210: Inheritance Between "Classes": Constructor Functions
- [x] Section 14 Coding Challenge 3

🛑Do not continue until Section 14 Coding Challenge 3 has been completed

- [x] Watch Lecture 211: Coding Challenge 3
- [x] Watch Lecture 212: Inheritance Between "Classes": ES6 Classes
- [x] Watch Lecture 213: Inheritance Between "Classes": Object.create
- [x] Watch Lecture 214: Another Class Example
- [x] Watch Lecture 215: Encapsulation: Protected Properties and Methods
- [x] Watch Lecture 216: Encapsulation: Private Class Fields and Methods
- [x] Watch Lecture 217: Chaining Methods
- [x] Watch Lecture 218: ES6 Classes Summary
- [x] Section 14 Coding Challenge 4

🛑Do not continue until Section 14 Coding Challenge 4 has been completed

- [x] Watch Lecture 219: Coding Challenge 4

**Section 15: Mapty App: OOP, Geolocation, External Libraries, and More**
- [x] [Download Starter files](https://github.com/jonasschmedtmann/complete-javascript-course/tree/master/15-Mapty/starter) for Mapty App. Follow along with lectures (222 thru 235) 
- [x] Watch Lecture 222 PROJECT: Overview (Mapty)
- [x] Watch Lecture 223: How to Plan a Web Project
- [x] Watch Lecture 224: Using the Geolocation API
- [x] Watch Lecture 225: Displaying a Map using Leaflet Library
- [x] Watch Lecture 226: Displaying a Map Marker
- [x] Watch Lecture 227: Rendering Workout Input Form
- [x] Watch Lecture 228: Project Architecture
- [x] Watch Lecture 229: Refactoring for Project Architecture
- [x] Watch Lecture 230: Managing Workout Data: Creating Classes
- [x] Watch Lecture 231: Creating a New Workout
- [x] Watch Lecture 232: Rendering Workouts
- [x] Watch Lecture 233: Move to Marker on Click
- [x] Watch Lecture 234: Working with localStorage
- [x] Watch Lecture 235: Final Considerations
- [x] Section 15 Project: Push the updated code for the Mapty App to your new branch, Section15Project
- [x] Section 15 Project Additional Features #3 

**Section 16: Asynchronous JavaScript: Promises, Async/Await, and AJAX**
- [x] [Download Starter files](https://github.com/jonasschmedtmann/complete-javascript-course/tree/master/16-Asynchronous/starter) for Asynchronous App. Follow along with lectures (246 thru 267) 
- [x] Watch Lecture 238: Asynchronous Javascript, AJAX and APIs
- [x] Watch Lecture 239: IMPORTANT: API URL Change
- [x] Watch Lecture 240: Our First AJAX Call: XMLHttpRequest
- [x] Watch Lecture 241: [OPTIONAL] How the Web Works: Requests and Responses
- [x] Watch Lecture 242: Welcome to Callback Hell
- [x] Watch Lecture 243: Promises and the Fetch API
- [x] Watch Lecture 244: Consuming Promises
- [x] Watch Lecture 245: Chaining Promises
- [x] Watch Lecture 246: Handling Rejected Promises
- [x] Watch Lecture 247: Throwing Errors Manually
- [x] Section 16 Coding Challenge 1

🛑Do not continue until Section 16 Coding Challenge 1 has been completed

- [x] Watch Lecture 248: Coding Challenge 1
- [x] Watch Lecture 249: Asynchronous Behind the Scenes: The Event Loop
- [x] Watch Lecture 250: The Event Loop in Practice
- [x] Watch Lecture 251: Building a Simple Promise
- [x] Watch Lecture 252: Promisfying the Geolocation API
- [x] Section 16 Coding Challenge 2 (Watch first 5 minutes of Lecture 261 then pause ... images are in the starter files for Section 16 downloaded from above)

🛑Do not continue until Section 16 Coding Challenge 2 has been completed

- [x] Watch Lecture 253: Coding Challenge 2
- [x] Watch Lecture 254: Consuming Promises with Async/Await
- [x] Watch Lecture 255: Error Handling with try...catch
- [x] Watch Lecture 256: Returning Values from Async Functions
- [x] Watch Lecture 257: Running Promises in Parallel
- [x] Watch Lecture 258: Other Promise Combinators: race, allSettled and any
- [x] Section 16 Coding Challenge 3 (images are in the starter files for Section 16 downloaded from above)

🛑Do not continue until Section 16 Coding Challenge 3 has been completed

- [x] Watch Lecture 259: Coding Challenge 3

**Section 17: Modern JavaScript Development: Modules, Tooling, and Functional**

- [x] [Download Starter files](https://github.com/jonasschmedtmann/complete-javascript-course/tree/master/17-Modern-JS-Modules-Tooling/starter) for Modern JavaScript Development Modules, Tooling, and Functional. Follow along with lectures (270 thru 283) 
- [x] Watch Lecture 262: An Overview of Modern JavaScript Development
- [x] Watch Lecture 263: An Overview of Modules in JavaScript
- [x] Watch Lecture 264: Exporting and Importing in ES6 Modules
- [x] Watch Lecture 265: Top-Level await (ES2022)
- [x] Watch Lecture 266: The Module Pattern
- [x] Watch Lecture 267: CommonJS Modules
- [x] Watch Lecture 268: A Brief Introduction to the Command Line
- [x] Watch Lecture 269: Introduction to NPM
- [ ] Watch Lecture 270: Bundling With Parcel and NPM Scripts
- [ ] Watch Lecture 271:  Configuring Babel and Polyfilling
- [ ] Watch Lecture 272: Review: Writing Clean and Modern JavaScript
- [ ] Watch Lecture 273: Let's Fix Some Bad Code: Part 1
- [ ] Watch Lecture 274: Declarative and Functional JavaScript Principles
- [ ] Watch Lecture 275: Let's Fix Some Bad Code: Part 2

**Section 18: Forkify App: Building a Modern Application**
- [ ] [Download Starter files](https://github.com/jonasschmedtmann/complete-javascript-course/tree/updates-and-fixes/18-forkify/starter) for Forkify App. Follow along with lectures (278 thru 302) 
- [ ] Watch Lecture 278: Project Overview and Planning (I)
- [ ] Watch Lecture 279: Latest Code Updates (Parcel v2 and More)
- [ ] Watch Lecture 280: Loading a Recipe from API (install Parcel 2 .. npm i parcel@2 -D)
- [ ] Watch Lecture 281: Rending the Recipe
- [ ] Watch Lecture 282: Listening For load and hashchange Events
- [ ] Watch Lecture 283: The MVC Architecture
- [ ] Watch Lecture 284: Refactoring for MVC
- [ ] Watch Lecture 285: Helpers and Configuration Files
- [ ] Watch Lecture 286: Event Handlers in MVC: Publisher-Subscriber Pattern
- [ ] Watch Lecture 287: Implementing Error and Success Messages
- [ ] Watch Lecture 288: Implementing Search Results - Part 1
- [ ] Watch Lecture 289: Implementing Search Results - Part 2
- [ ] Watch Lecture 290: Implementing Pagination - Part 1
- [ ] Watch Lecture 291: Implementing Pagination - Part 2
- [ ] Watch Lecture 292: Project Planning II
- [ ] Watch Lecture 293: Updating Recipe Servings
- [ ] Watch Lecture 294: Developing a DOM Updating Algorithm
- [ ] Watch Lecture 295: Implementing Bookmarks - Part 1
- [ ] Watch Lecture 296: Implementing Bookmarks - Part 2
- [ ] Watch Lecture 297: Storing Bookmarks With localStorage
- [ ] Watch Lecture 298: Project Planning III
- [ ] Watch Lecture 299: Uploading a New Recipe - Part 1
- [ ] Watch Lecture 300: Uploading a New Recipe - Part 2
- [ ] Watch Lecture 301: Uploading a New Receipt - Part 3
- [ ] Watch Lecture 302: Wrapping Up: Final Considerations
- [ ] Section 18 Project: Push the updated code for the Forkify App to your new branch, Section18Project
- [ ] Section 18 Project Additional Features #4 

**Section 19: Setting Up Git and Deployment**
- [ ] Watch Lecture 305: Simple Deployment With Netlify
- [ ] Setup Account with Netlify. Deploy Forkify App with additional features.
- [ ] Watch Lecture 306: Setting Up Git and GitHub
- [ ] Watch Lecture 307: Git Fundamentals
- [ ] Watch Lecture 308: Pushing to GitHub
- [ ] Watch Lecture 309: Setting Up Continuous Integration with Netlify
- [ ] Section 19 Assignment #5 

**Section 20: The End!**
